config .yml infrastructure

diff --git a/.github/workflows/deployInfrastructure.yml b/.github/workflows/deployInfrastructure.yml
--- a/.github/workflows/deployInfrastructure.yml
+++ b/.github/workflows/deployInfrastructure.yml
@@ -59,20 +59,23 @@ jobs:
 
       - name: Validate Infrastructure
         run: |
-            # Verificar el estado de Cloud Functions
-            gcloud functions list
+          # Verificar el estado de Cloud Functions
+          gcloud functions list
 
-            # Verificar el estado de API Gateway
-            gcloud api-gateway gateways list
+          # Verificar el estado de API Gateway
+          gcloud api-gateway gateways list
 
-            # Verificar el estado de Cloud Storage
-            gcloud storage buckets list
+          # Verificar el estado de Cloud Storage
+          gcloud storage buckets list
 
+          gcloud redis instances describe my-redis-instance --region=us-central1
 
-            # Verificar el resultado de la validación
-            if [ $? -eq 0 ]; then
-              echo "Infrastructure validation passed. Infrastructure is updated successfully."
-            else
-              echo "Infrastructure validation failed. There might be issues with the updated infrastructure."
-              exit 1
-            fi
+          gcloud sql instances describe my-db-instance --format="value(state)"
+
+          # Verificar el resultado de la validación
+          if [ $? -eq 0 ]; then
+            echo "Infrastructure validation passed. Infrastructure is updated successfully."
+          else
+            echo "Infrastructure validation failed. There might be issues with the updated infrastructure."
+            exit 1
+          fi
